version: '3'
services:
  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=scraper
      - MONGO_INITDB_ROOT_USERNAME=rootscraper
      - MONGO_INITDB_ROOT_PASSWORD=rootP4sw0rd
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      #- ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'